name: Update Version Badge

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'package.json'  # Only run when package.json changes

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Update README badge
        run: |
          # Replace the version badge in README.md
          VERSION="${{ steps.package-version.outputs.current-version }}"
          
          # Use sed to replace the version in the badge URL
          sed -i "s/version-[0-9]\+\.[0-9]\+\.[0-9]\+/version-${VERSION}/g" README.md
          
          # Verify the change was made
          grep "version-" README.md

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Update version badge to v${{ steps.package-version.outputs.current-version }}"
          git push
